import type {
  LearningLog,
  LearningResource,
  LearningResourceType,
  LearningUnit,
  NewLearningLogInput,
  NewLearningResourceInput,
  NewSkillAreaInput,
  ResourceWithProgress,
  SkillArea,
  SkillAreaSummary,
  UpdateLearningLogInput,
  UpdateLearningResourceInput,
  UpdateSkillAreaInput,
} from "@lifeos/contracts";

export type {
  LearningLog,
  LearningResource,
  LearningResourceType,
  LearningUnit,
  NewLearningLogInput,
  NewLearningResourceInput,
  NewSkillAreaInput,
  ResourceWithProgress,
  SkillArea,
  SkillAreaSummary,
  UpdateLearningLogInput,
  UpdateLearningResourceInput,
  UpdateSkillAreaInput,
};
